api_version = "2026-01"

[[extensions]]
name = "Workbench product discount example"
handle = "workbench-product-discount"
type = "function"
description = "Official example function for Shopify Functions Workbench"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
